import logging
from fastapi import APIRouter
from app.core.db_utils import DBConnection
from app.schemas.week_to_date.pos_entry_form.form_pos_select_schema import FormPOSSelectRequest, FormPOSSelectResponse

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/week_to_date/pos_entry_form",
    tags=["Week To Date POS Entry Form"]
)

@router.post("/form_pos_select", response_model=FormPOSSelectResponse)
def csa_form_pos_select(request: FormPOSSelectRequest):
    """
    Equivalent of:
    csa_FormPOS_Select
    """
    try:
        if request.pos_store is None:
            return FormPOSSelectResponse(
                return_value=1,
                error_message="Invalid Store"
            )
            
        if request.pos_file_date is None:
            return FormPOSSelectResponse(
                return_value=2,
                error_message="Invalid Date"
            )

        with DBConnection() as conn:
            with conn.cursor() as cur:
                # Check if row exists
                cur.execute("""
                    SELECT count(*)
                    FROM retail_history.pos
                    WHERE pos_store = %s AND pos_file_date = %s
                """, (request.pos_store, request.pos_file_date))
                
                count_record = cur.fetchone()
                if not count_record or count_record[0] == 0:
                    return FormPOSSelectResponse(
                        return_value=3,
                        error_message="Row not found"
                    )

                # Retrieve attributes
                cur.execute("""
                    SELECT 	pos_store,
                            pos_file_date,
                            pos_process_flag,
                            pos_current_reading,
                            pos_previous_reading_prior_day,
                            pos_previous_reading_prior_week,
                            pos_wtd_net_sales_rate_1,
                            pos_wtd_net_sales_rate_2,
                            pos_wtd_net_sales_rate_3,
                            pos_wtd_net_sales_rate_4,
                            pos_wtd_voids_rate_1,
                            pos_wtd_voids_rate_2,
                            pos_wtd_voids_rate_3,
                            pos_wtd_voids_rate_4,
                            pos_wtd_nt_refunds_rate_1,
                            pos_wtd_nt_refunds_rate_2,
                            pos_wtd_nt_refunds_rate_3,
                            pos_wtd_nt_refunds_rate_4,
                            pos_wtd_refunds_rate_1,
                            pos_wtd_refunds_rate_2,
                            pos_wtd_refunds_rate_3,
                            pos_wtd_refunds_rate_4,
                            pos_wtd_credits_rate_1,
                            pos_wtd_credits_rate_2,
                            pos_wtd_credits_rate_3,
                            pos_wtd_credits_rate_4,
                            pos_wtd_bottle_deposits,
                            pos_wtd_bottle_refunds,
                            pos_wtd_store_coupons,
                            pos_wtd_grocery_sales,
                            pos_wtd_grocery_voids_refunds,
                            pos_wtd_meat_sales,
                            pos_wtd_meat_voids_refunds,
                            pos_wtd_produce_sales,
                            pos_wtd_produce_voids_refunds,
                            pos_wtd_deli_bakery_sales,
                            pos_wtd_deli_bakery_voids_refunds,
                            pos_wtd_florist_sales,
                            pos_wtd_florist_voids_refunds,
                            pos_wtd_seafood_sales,
                            pos_wtd_seafood_voids_refunds,
                            pos_wtd_pharmacy_sales,
                            pos_wtd_pharmacy_voids_refunds,
                            pos_wtd_ff_dairy_sales,
                            pos_wtd_ff_dairy_voids_refunds,
                            pos_wtd_hba_sales,
                            pos_wtd_hba_voids_refunds,
                            pos_wtd_sales_tax_collected_rate_1,
                            pos_wtd_sales_tax_collected_rate_2,
                            pos_wtd_sales_tax_collected_rate_3,
                            pos_wtd_sales_tax_collected_rate_4,
                            pos_wtd_total_customer_count,
                            pos_wtd_grocery_customer_count,
                            pos_wtd_meat_customer_count,
                            pos_wtd_produce_customer_count,
                            pos_wtd_deli_customer_count,
                            pos_wtd_florist_customer_count,
                            pos_wtd_seafood_customer_count,
                            pos_wtd_pharmacy_customer_count,
                            pos_wtd_ff_dairy_customer_count,
                            pos_wtd_hba_customer_count,
                            pos_wtd_item_count,
                            pos_wtd_nt_sales_rate_1,
                            pos_wtd_nt_sales_rate_2,
                            pos_wtd_nt_sales_rate_3,
                            pos_wtd_nt_sales_rate_4,
                            pos_daily_net_sales_rate_1,
                            pos_daily_net_sales_rate_2,
                            pos_daily_net_sales_rate_3,
                            pos_daily_net_sales_rate_4,
                            pos_daily_voids_rate_1,
                            pos_daily_voids_rate_2,
                            pos_daily_voids_rate_3,
                            pos_daily_voids_rate_4,
                            pos_daily_nt_refunds_rate_1,
                            pos_daily_nt_refunds_rate_2,
                            pos_daily_nt_refunds_rate_3,
                            pos_daily_nt_refunds_rate_4,
                            pos_daily_refunds_rate_1,
                            pos_daily_refunds_rate_2,
                            pos_daily_refunds_rate_3,
                            pos_daily_refunds_rate_4,
                            pos_daily_credits_rate_1,
                            pos_daily_credits_rate_2,
                            pos_daily_credits_rate_3,
                            pos_daily_credits_rate_4,
                            pos_daily_bottle_deposits,
                            pos_daily_bottle_returns,
                            pos_daily_store_coupons,
                            pos_daily_grocery_sales,
                            pos_daily_grocery_voids_refunds,
                            pos_daily_meat_sales,
                            pos_daily_meat_voids_refunds,
                            pos_daily_produce_sales,
                            pos_daily_produce_voids_refunds,
                            pos_daily_deli_bakery_sales,
                            pos_daily_deli_bakery_voids_refunds,
                            pos_daily_florist_sales,
                            pos_daily_florist_voids_refunds,
                            pos_daily_seafood_sales,
                            pos_daily_seafood_voids_refunds,
                            pos_daily_pharmacy_sales,
                            pos_daily_pharmacy_voids_refunds,
                            pos_daily_ff_dairy_sales,
                            pos_daily_ff_dairy_voids_refunds,
                            pos_daily_hba_sales,
                            pos_daily_hba_voids_refunds,
                            pos_daily_sales_tax_collected_rate_1,
                            pos_daily_sales_tax_collected_rate_2,
                            pos_daily_sales_tax_collected_rate_3,
                            pos_daily_sales_tax_collected_rate_4,
                            pos_daily_total_customer_count,
                            pos_daily_grocery_customer_count,
                            pos_daily_meat_customer_count,
                            pos_daily_produce_customer_count,
                            pos_daily_deli_customer_count,
                            pos_daily_florist_customer_count,
                            pos_daily_seafood_customer_count,
                            pos_daily_pharmacy_customer_count,
                            pos_daily_ff_dairy_customer_count,
                            pos_daily_hba_customer_count,
                            pos_daily_item_count,
                            pos_wtd_sushi_sales,
                            pos_wtd_sushi_voids_refunds,
                            pos_wtd_sushi_customer_count,
                            pos_wtd_fuel_sales,
                            pos_wtd_fuel_voids_refunds,
                            pos_wtd_fuel_customer_count,
                            pos_wtd_starbucks_sales,
                            pos_wtd_starbucks_voids_refunds,
                            pos_wtd_starbucks_customer_count,
                            pos_wtd_kitchen_ware_sales,
                            pos_wtd_kitchen_ware_voids_refunds,
                            pos_wtd_kitchen_ware_customer_count,
                            pos_wtd_dream_dinners_sales,
                            pos_wtd_dream_dinners_voids_refunds,
                            pos_wtd_dream_dinners_customer_count,
                            pos_daily_sushi_sales,
                            pos_daily_sushi_voids_refunds,
                            pos_daily_sushi_customer_count,
                            pos_daily_fuel_sales,
                            pos_daily_fuel_voids_refunds,
                            pos_daily_fuel_customer_count,
                            pos_daily_starbucks_sales,
                            pos_daily_starbucks_voids_refunds,
                            pos_daily_starbucks_customer_count,
                            pos_daily_kitchen_ware_sales,
                            pos_daily_kitchen_ware_voids_refunds,
                            pos_daily_kitchen_ware_customer_count,
                            pos_daily_dream_dinners_sales,
                            pos_daily_dream_dinners_voids_refunds,
                            pos_daily_dream_dinners_customer_count,
                            pos_wtd_void_transaction,
                            pos_daily_void_transaction
                    FROM retail_history.pos
                    WHERE pos_store = %s AND pos_file_date = %s
                """, (request.pos_store, request.pos_file_date))
                
                row = cur.fetchone()
                if row:
                    return FormPOSSelectResponse(
                        return_value=0,
                        error_message="",
                        pos_store=row[0],
                        pos_file_date=row[1],
                        pos_process_flag=row[2],
                        pos_current_reading=row[3],
                        pos_previous_reading_prior_day=row[4],
                        pos_previous_reading_prior_week=row[5],
                        pos_wtd_net_sales_rate_1=row[6],
                        pos_wtd_net_sales_rate_2=row[7],
                        pos_wtd_net_sales_rate_3=row[8],
                        pos_wtd_net_sales_rate_4=row[9],
                        pos_wtd_voids_rate_1=row[10],
                        pos_wtd_voids_rate_2=row[11],
                        pos_wtd_voids_rate_3=row[12],
                        pos_wtd_voids_rate_4=row[13],
                        pos_wtd_nt_refunds_rate_1=row[14],
                        pos_wtd_nt_refunds_rate_2=row[15],
                        pos_wtd_nt_refunds_rate_3=row[16],
                        pos_wtd_nt_refunds_rate_4=row[17],
                        pos_wtd_refunds_rate_1=row[18],
                        pos_wtd_refunds_rate_2=row[19],
                        pos_wtd_refunds_rate_3=row[20],
                        pos_wtd_refunds_rate_4=row[21],
                        pos_wtd_credits_rate_1=row[22],
                        pos_wtd_credits_rate_2=row[23],
                        pos_wtd_credits_rate_3=row[24],
                        pos_wtd_credits_rate_4=row[25],
                        pos_wtd_bottle_deposits=row[26],
                        pos_wtd_bottle_refunds=row[27],
                        pos_wtd_store_coupons=row[28],
                        pos_wtd_grocery_sales=row[29],
                        pos_wtd_grocery_voids_refunds=row[30],
                        pos_wtd_meat_sales=row[31],
                        pos_wtd_meat_voids_refunds=row[32],
                        pos_wtd_produce_sales=row[33],
                        pos_wtd_produce_voids_refunds=row[34],
                        pos_wtd_deli_bakery_sales=row[35],
                        pos_wtd_deli_bakery_voids_refunds=row[36],
                        pos_wtd_florist_sales=row[37],
                        pos_wtd_florist_voids_refunds=row[38],
                        pos_wtd_seafood_sales=row[39],
                        pos_wtd_seafood_voids_refunds=row[40],
                        pos_wtd_pharmacy_sales=row[41],
                        pos_wtd_pharmacy_voids_refunds=row[42],
                        pos_wtd_ff_dairy_sales=row[43],
                        pos_wtd_ff_dairy_voids_refunds=row[44],
                        pos_wtd_hba_sales=row[45],
                        pos_wtd_hba_voids_refunds=row[46],
                        pos_wtd_sales_tax_collected_rate_1=row[47],
                        pos_wtd_sales_tax_collected_rate_2=row[48],
                        pos_wtd_sales_tax_collected_rate_3=row[49],
                        pos_wtd_sales_tax_collected_rate_4=row[50],
                        pos_wtd_total_customer_count=row[51],
                        pos_wtd_grocery_customer_count=row[52],
                        pos_wtd_meat_customer_count=row[53],
                        pos_wtd_produce_customer_count=row[54],
                        pos_wtd_deli_customer_count=row[55],
                        pos_wtd_florist_customer_count=row[56],
                        pos_wtd_seafood_customer_count=row[57],
                        pos_wtd_pharmacy_customer_count=row[58],
                        pos_wtd_ff_dairy_customer_count=row[59],
                        pos_wtd_hba_customer_count=row[60],
                        pos_wtd_item_count=row[61],
                        pos_wtd_nt_sales_rate_1=row[62],
                        pos_wtd_nt_sales_rate_2=row[63],
                        pos_wtd_nt_sales_rate_3=row[64],
                        pos_wtd_nt_sales_rate_4=row[65],
                        pos_daily_net_sales_rate_1=row[66],
                        pos_daily_net_sales_rate_2=row[67],
                        pos_daily_net_sales_rate_3=row[68],
                        pos_daily_net_sales_rate_4=row[69],
                        pos_daily_voids_rate_1=row[70],
                        pos_daily_voids_rate_2=row[71],
                        pos_daily_voids_rate_3=row[72],
                        pos_daily_voids_rate_4=row[73],
                        pos_daily_nt_refunds_rate_1=row[74],
                        pos_daily_nt_refunds_rate_2=row[75],
                        pos_daily_nt_refunds_rate_3=row[76],
                        pos_daily_nt_refunds_rate_4=row[77],
                        pos_daily_refunds_rate_1=row[78],
                        pos_daily_refunds_rate_2=row[79],
                        pos_daily_refunds_rate_3=row[80],
                        pos_daily_refunds_rate_4=row[81],
                        pos_daily_credits_rate_1=row[82],
                        pos_daily_credits_rate_2=row[83],
                        pos_daily_credits_rate_3=row[84],
                        pos_daily_credits_rate_4=row[85],
                        pos_daily_bottle_deposits=row[86],
                        pos_daily_bottle_returns=row[87],
                        pos_daily_store_coupons=row[88],
                        pos_daily_grocery_sales=row[89],
                        pos_daily_grocery_voids_refunds=row[90],
                        pos_daily_meat_sales=row[91],
                        pos_daily_meat_voids_refunds=row[92],
                        pos_daily_produce_sales=row[93],
                        pos_daily_produce_voids_refunds=row[94],
                        pos_daily_deli_bakery_sales=row[95],
                        pos_daily_deli_bakery_voids_refunds=row[96],
                        pos_daily_florist_sales=row[97],
                        pos_daily_florist_voids_refunds=row[98],
                        pos_daily_seafood_sales=row[99],
                        pos_daily_seafood_voids_refunds=row[100],
                        pos_daily_pharmacy_sales=row[101],
                        pos_daily_pharmacy_voids_refunds=row[102],
                        pos_daily_ff_dairy_sales=row[103],
                        pos_daily_ff_dairy_voids_refunds=row[104],
                        pos_daily_hba_sales=row[105],
                        pos_daily_hba_voids_refunds=row[106],
                        pos_daily_sales_tax_collected_rate_1=row[107],
                        pos_daily_sales_tax_collected_rate_2=row[108],
                        pos_daily_sales_tax_collected_rate_3=row[109],
                        pos_daily_sales_tax_collected_rate_4=row[110],
                        pos_daily_total_customer_count=row[111],
                        pos_daily_grocery_customer_count=row[112],
                        pos_daily_meat_customer_count=row[113],
                        pos_daily_produce_customer_count=row[114],
                        pos_daily_deli_customer_count=row[115],
                        pos_daily_florist_customer_count=row[116],
                        pos_daily_seafood_customer_count=row[117],
                        pos_daily_pharmacy_customer_count=row[118],
                        pos_daily_ff_dairy_customer_count=row[119],
                        pos_daily_hba_customer_count=row[120],
                        pos_daily_item_count=row[121],
                        pos_wtd_sushi_sales=row[122],
                        pos_wtd_sushi_voids_refunds=row[123],
                        pos_wtd_sushi_customer_count=row[124],
                        pos_wtd_fuel_sales=row[125],
                        pos_wtd_fuel_voids_refunds=row[126],
                        pos_wtd_fuel_customer_count=row[127],
                        pos_wtd_starbucks_sales=row[128],
                        pos_wtd_starbucks_voids_refunds=row[129],
                        pos_wtd_starbucks_customer_count=row[130],
                        pos_wtd_kitchen_ware_sales=row[131],
                        pos_wtd_kitchen_ware_voids_refunds=row[132],
                        pos_wtd_kitchen_ware_customer_count=row[133],
                        pos_wtd_dream_dinners_sales=row[134],
                        pos_wtd_dream_dinners_voids_refunds=row[135],
                        pos_wtd_dream_dinners_customer_count=row[136],
                        pos_daily_sushi_sales=row[137],
                        pos_daily_sushi_voids_refunds=row[138],
                        pos_daily_sushi_customer_count=row[139],
                        pos_daily_fuel_sales=row[140],
                        pos_daily_fuel_voids_refunds=row[141],
                        pos_daily_fuel_customer_count=row[142],
                        pos_daily_starbucks_sales=row[143],
                        pos_daily_starbucks_voids_refunds=row[144],
                        pos_daily_starbucks_customer_count=row[145],
                        pos_daily_kitchen_ware_sales=row[146],
                        pos_daily_kitchen_ware_voids_refunds=row[147],
                        pos_daily_kitchen_ware_customer_count=row[148],
                        pos_daily_dream_dinners_sales=row[149],
                        pos_daily_dream_dinners_voids_refunds=row[150],
                        pos_daily_dream_dinners_customer_count=row[151],
                        pos_wtd_void_transaction=row[152],
                        pos_daily_void_transaction=row[153]
                    )
                else:
                    return FormPOSSelectResponse(
                        return_value=1,
                        error_message="Select Form POS Failed"
                    )

    except Exception as ex:
        logger.exception("Error in FormPOS_Select")
        return FormPOSSelectResponse(
            return_value=1,
            error_message="Select Form POS Failed"
        )
